/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ImageRecognizer: typeof import('./src/components/ImageRecognizer.vue')['default']
    VideoRecognizer: typeof import('./src/components/VideoRecognizer.vue')['default']
  }
}
